#!/usr/bin/python3
import sys, math
def do_prime(numbers):
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        exit()
    for number in numbers:
        number = int(number)
        if number % 2 == 0:
            print(f"{number}={number // 2}*2")
        elif number % 3 == 0:
            print(f"{number}={number // 3}*3")
        elif number % 5 == 0:
            print(f"{number}={number // 5}*5")
        elif number % 7 == 0:
            print(f"{number}={number // 7}*7")
        else:
            for n in range(3, int(math.sqrt(number)) + 1, 2):
                if number % n == 0:
                    print(f"{number}={number // n}*{n}")
                    break
if __name__ == "__main__":
    try:
        arg = sys.argv[1]
        fille = open(arg, "r")
        content = fille.readlines()
        do_prime(content)
        fille.close()
    except FileNotFoundError:
        print("File not found")
        exit()
