#!/usr/bin/python3
import sys, math
arg = sys.argv[1]
def do_prime(numbers):
    for number in numbers:
        number = int(number)
        if number % 2 == 0:
            print(f"{number}={number // 2}*2")
        elif number % 3 == 0:
            print(f"{number}={number // 3}*3")
        elif number % 5 == 0:
            print(f"{number}={number // 5}*5")
        elif number % 7 == 0:
            print(f"{number}={number // 7}*7")
        else:
            for n in range(2, int(math.sqrt(number)) + 1):
                if number % n == 0:
                    print(f"{number}={number // n}*{n}")
                    break
fille = open(arg, "r")
content = fille.readlines()
do_prime(content)
fille.close()
