#!/usr/bin/python3
import sys
import time


def isprime(number):
    if number < 2:
        return False
    for i in range(2, int(number ** 0.5) + 1):
        if number % i == 0:
            return False
    return True


def pfactor(number):
    number = int(number)
    if number % 2 == 0 and isprime(number // 2):
        print(f"{number}={number // 2}*{2}")
    else:
        for n in range(3, int(number ** 0.5) + 1, 2):
            if number % n == 0 and isprime(number // n):
                print(f"{number}={number // n}*{n}")
                exit(0)
        print(f"{number}={number // number}*{number}")


if __name__ == "__main__":
    try:
        if len(sys.argv) != 2:
            print("Usage: factors <file>")
            exit()
        arg = sys.argv[1]
        with open(arg, "r") as fille:
            content = fille.read()
        pfactor(content)
    except FileNotFoundError:
        print("File not found")
        exit()
